cmake_minimum_required(VERSION 3.20)
project(instProbe CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(OpenGL REQUIRED)
find_package(pxr CONFIG REQUIRED PATHS $USD)
add_executable(instProbe instProbe.cpp)
add_executable(instProbe2 instProbe2.cpp)
add_executable(instProbe3 instProbe3.cpp)
add_executable(instProbe4 instProbe4.cpp)
target_link_libraries(instProbe4 usd usdGeom usdImaging hd hdx hf hio hdSt cameraUtil tf sdf vt gf plug work trace)
target_include_directories(instProbe4 PRIVATE $USD/include)
target_link_libraries(instProbe3 usd usdGeom usdImaging hd hf hio hdSt cameraUtil tf sdf vt gf plug work trace)
target_include_directories(instProbe3 PRIVATE $USD/include)
target_link_libraries(instProbe2 usd usdGeom usdImaging hd hf hio hdSt cameraUtil tf sdf vt gf plug work trace)
target_include_directories(instProbe2 PRIVATE $USD/include)
target_link_libraries(instProbe
  usd usdGeom usdImaging hd hf hio hdSt cameraUtil tf sdf vt gf plug work trace)
target_include_directories(instProbe PRIVATE $USD/include)
