// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

#include "render/FontAtlas.h"

#include "stb_image.h"

#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"

#include <array>
#include <cstdio>


#include <cstdio>
#include "render/noodles_gl.h"
#include <mutex>

namespace noodles {
namespace {
#if NOODLES_USE_GLEW
// One-time GLEW initialization.  The host application provides the GL
// context; we just need to load function pointers via GLEW once for this
// process.  glewExperimental=GL_TRUE is required for core-profile contexts
// (e.g. Qt's QOpenGLWidget defaults), and the spurious INVALID_ENUM error
// generated by glGetString(GL_EXTENSIONS) on core profiles is cleared.
void ensureGlewInitialized() {
  static std::once_flag flag;
  std::call_once(flag, []() {
    glewExperimental = GL_TRUE;
    GLenum err = glewInit();
    if (err != GLEW_OK) {
      std::fprintf(
          stderr,
          "[noodles] glewInit() failed: %s\n",
          reinterpret_cast<const char*>(glewGetErrorString(err)));
      return;
    }
    while (glGetError() != GL_NO_ERROR) {
      // drain any GLEW-generated errors
    }
  });
}
#else
// Apple frameworks and GLES expose their entry points directly and do not use
// a process-global extension loader.
void ensureGlewInitialized() {}
#endif
}  // namespace
}  // namespace noodles

namespace noodles {

FontAtlas::~FontAtlas() {
  cleanup();
}

FontAtlas::FontAtlas(FontAtlas&& other) noexcept
    : textureId_(other.textureId_),
      glyphs_(std::move(other.glyphs_)),
      pxRange_(other.pxRange_),
      lineHeight_(other.lineHeight_),
      ascender_(other.ascender_),
      descender_(other.descender_) {
  other.textureId_ = 0;
}

FontAtlas& FontAtlas::operator=(FontAtlas&& other) noexcept {
  if (this != &other) {
    cleanup();
    textureId_ = other.textureId_;
    glyphs_ = std::move(other.glyphs_);
    pxRange_ = other.pxRange_;
    lineHeight_ = other.lineHeight_;
    ascender_ = other.ascender_;
    descender_ = other.descender_;
    other.textureId_ = 0;
  }
  return *this;
}

void FontAtlas::initialize(const std::string& atlasPath, const std::string& jsonPath) {
  ensureGlewInitialized();
  loadAtlas(atlasPath);
  loadMetrics(jsonPath);
}

void FontAtlas::loadAtlas(const std::string& atlasPath) {
  int width = 0, height = 0, channels = 0;
  unsigned char* data = stbi_load(atlasPath.c_str(), &width, &height, &channels, 4);
  if (!data) {
    return;
  }

  glGenTextures(1, &textureId_);
  glBindTexture(GL_TEXTURE_2D, textureId_);

  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);

  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, data);

  glGenerateMipmap(GL_TEXTURE_2D);
  glBindTexture(GL_TEXTURE_2D, 0);

  stbi_image_free(data);
}

void FontAtlas::loadMetrics(const std::string& jsonPath) {
  FILE* fp = fopen(jsonPath.c_str(), "rb");
  if (!fp) {
    return;
  }

  std::array<char, 65536> readBuffer{};
  rapidjson::FileReadStream is(fp, readBuffer.data(), readBuffer.size());
  rapidjson::Document doc;
  doc.ParseStream(is);
  fclose(fp);

  if (doc.HasParseError()) {
    return;
  }

  double atlasWidth = 1.0, atlasHeight = 1.0;
  if (doc.HasMember("atlas") && doc["atlas"].IsObject()) {
    const auto& atlas = doc["atlas"];
    if (atlas.HasMember("width")) {
      atlasWidth = atlas["width"].GetDouble();
    }
    if (atlas.HasMember("height")) {
      atlasHeight = atlas["height"].GetDouble();
    }
    if (atlas.HasMember("distanceRange")) {
      pxRange_ = atlas["distanceRange"].GetDouble();
    }
  }

  if (doc.HasMember("metrics") && doc["metrics"].IsObject()) {
    const auto& metrics = doc["metrics"];
    if (metrics.HasMember("lineHeight")) {
      lineHeight_ = metrics["lineHeight"].GetDouble();
    }
    if (metrics.HasMember("ascender")) {
      ascender_ = metrics["ascender"].GetDouble();
    }
    if (metrics.HasMember("descender")) {
      descender_ = metrics["descender"].GetDouble();
    }
  }

  if (doc.HasMember("glyphs") && doc["glyphs"].IsArray()) {
    for (const auto& glyphData : doc["glyphs"].GetArray()) {
      Glyph glyph;
      if (glyphData.HasMember("unicode")) {
        glyph.unicode = glyphData["unicode"].GetInt();
      }

      if (glyphData.HasMember("advance")) {
        glyph.advance = glyphData["advance"].GetDouble();
      }

      if (glyphData.HasMember("planeBounds") && glyphData["planeBounds"].IsObject()) {
        const auto& pb = glyphData["planeBounds"];
        double left = pb.HasMember("left") ? pb["left"].GetDouble() : 0;
        double top = pb.HasMember("top") ? pb["top"].GetDouble() : 0;
        double right = pb.HasMember("right") ? pb["right"].GetDouble() : 0;
        double bottom = pb.HasMember("bottom") ? pb["bottom"].GetDouble() : 0;
        glyph.planeBounds = Range2d(Vec2d(left, top), Vec2d(right, bottom));
      }

      if (glyphData.HasMember("atlasBounds") && glyphData["atlasBounds"].IsObject()) {
        const auto& ab = glyphData["atlasBounds"];
        double leftNorm = (ab.HasMember("left") ? ab["left"].GetDouble() : 0) / atlasWidth;
        double bottomNorm = (ab.HasMember("bottom") ? ab["bottom"].GetDouble() : 0) / atlasHeight;
        double rightNorm = (ab.HasMember("right") ? ab["right"].GetDouble() : 0) / atlasWidth;
        double topNorm = (ab.HasMember("top") ? ab["top"].GetDouble() : 0) / atlasHeight;

        glyph.atlasBounds =
            Range2d(Vec2d(leftNorm, 1.0 - bottomNorm), Vec2d(rightNorm, 1.0 - topNorm));
      }

      glyphs_[glyph.unicode] = glyph;
    }
  }
}

void FontAtlas::bindTexture(int textureUnit) const {
  glActiveTexture(GL_TEXTURE0 + textureUnit);
  glBindTexture(GL_TEXTURE_2D, textureId_);
}

void FontAtlas::unbindTexture() const {
  glBindTexture(GL_TEXTURE_2D, 0);
}

void FontAtlas::cleanup() {
  if (textureId_) {
    glDeleteTextures(1, &textureId_);
    textureId_ = 0;
  }
  glyphs_.clear();
}

} // namespace noodles
