#include "usdGen/vulkan/lengthScalePipeline.h"
#include "usdGen/vulkan/sourceGeneration.h"
#include "vulkanReadbackFixture.h"
#include "floatUlpFixture.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iterator>
#include <map>
#include <limits>
#include <string>
#include <vector>

using namespace usdGen;
using namespace usdGen::vulkan;
#define CHECK(x) do { if (!(x)) { std::fprintf(stderr, "Vulkan reparam failed: %s (%d)\n", #x, __LINE__); std::abort(); } } while (false)
namespace {
template<class T> std::vector<uint8_t> Bytes(T const* p, size_t n) { std::vector<uint8_t> r(n*sizeof(T)); if (!r.empty()) std::memcpy(r.data(),p,r.size()); return r; }
static std::vector<uint32_t> Code(char const* p) { std::ifstream f(p,std::ios::binary); std::vector<char> b((std::istreambuf_iterator<char>(f)),{}); if(b.empty()||b.size()%4)return{}; std::vector<uint32_t> r(b.size()/4); std::memcpy(r.data(),b.data(),b.size()); return r; }
static bool Prove(std::shared_ptr<NativeOwner> const& n) { if(vkResetFences(n->device,1,&n->fence)!=VK_SUCCESS)return false; VkSubmitInfo s{};s.sType=VK_STRUCTURE_TYPE_SUBMIT_INFO;return vkQueueSubmit(n->queue,1,&s,n->fence)==VK_SUCCESS&&vkWaitForFences(n->device,1,&n->fence,VK_TRUE,10000000000ull)==VK_SUCCESS; }
static bool CheckPoints(std::vector<uint8_t> const& bytes, float const* expected) {
 CHECK(bytes.size()==21*sizeof(float));
 bool equal=FloatBytesWithinUlps(bytes.data(),expected,bytes.size(),4);
 for(size_t i=0;i<21;++i) {
  float actual; std::memcpy(&actual,bytes.data()+i*sizeof(float),sizeof(float));
  if(!equal && actual!=expected[i]) std::fprintf(stderr,"point[%zu] actual %.9g (%a), expected %.9g (%a)\n",i,actual,actual,expected[i],expected[i]);
 }
 return equal;
}
static void CheckUlpBounds() {
 float one=1.f, next=std::nextafter(one,2.f), two=std::nextafter(next,2.f);
 CHECK(FloatBytesWithinUlps(&one,&next,4,1));
 CHECK(!FloatBytesWithinUlps(&one,&two,4,1));
 float negative=-one, negativeNext=-next;
 CHECK(FloatBytesWithinUlps(&negative,&negativeNext,4,1));
 float zero=0.f, small=1e-6f, nan=std::numeric_limits<float>::quiet_NaN();
 CHECK(!FloatBytesWithinUlps(&zero,&small,4,4));
 CHECK(!FloatBytesWithinUlps(&nan,&nan,4,4));
 CHECK(!FloatBytesWithinUlps(&one,&one,3,4));
}
using Packet=std::map<std::string,std::vector<uint8_t>>;
static bool Capture(std::shared_ptr<NativeOwner> const& n,std::shared_ptr<DeviceContext> const& c,std::shared_ptr<const VulkanSourceGeneration> const& g,Packet*out){out->clear();auto add=[&](VulkanSourceGeneration::PlaneView const&p){std::vector<uint8_t>b;return ReadVulkanBytes(n,c,p.buffer,p.bytes,g,&b)&&out->emplace(p.metadata.name,std::move(b)).second;};for(auto const&p:g->planes())if(!add(p))return false;for(auto const&p:g->sourceFrames())if(!add(p))return false;return true;}
static VulkanSourceGenerationCreateInfo Source(std::shared_ptr<DeviceContext> c,bool zero=false,bool noHair=false){
 VulkanSourceGenerationCreateInfo i;i.context=std::move(c);auto&s=i.source;s.totalCurves=2;s.totalCvs=7;s.topologyVersion=93;s.valueVersion=17;s.cvOffsets={0,3,7};s.curveId={401,907};s.rootPrim={12,44};s.rootUV={{.2f,.3f},{.7f,.8f}};s.rootT={{1,0,0},{0,1,0}};s.rootB={{0,1,0},{0,0,1}};s.rootN={{0,0,1},{1,0,0}};UsdGenPlane maskPlane; maskPlane.name = TfToken("curveMask"); maskPlane.interpolation = TfToken("uniform"); maskPlane.type = TfToken("float"); maskPlane.f = {{.25f,.75f}};s.px=zero?VtFloatArray(7,0):VtFloatArray{0,1,1,10,11,12,14};s.py=zero?VtFloatArray(7,0):VtFloatArray{0,0,3,0,0,0,0};s.pz=VtFloatArray(7,0);s.rest={GfVec3f(0,0,0),GfVec3f(0,10,0),GfVec3f(0,30,0),GfVec3f(9,9,9),GfVec3f(19,9,9),GfVec3f(29,9,9),GfVec3f(49,9,9)};s.width=VtFloatArray(7,1);if(!noHair)s.hairT={0,.75f,1,.5f,0,.75f,.25f};UsdGenChunkDesc x;x.firstCurve=0;x.curveCount=2;x.liveCount=2;x.firstCv=0;x.cvCount=0;x.tile=3;x.surface=1;s.chunks={x};UsdGenPlane p;p.name=TfToken("privateVertex");p.interpolation=TfToken("vertex");p.type=TfToken("float");p.arity=1;p.f={3,4,5,6,7,8,9};s.extraCv={p};UsdGenPlane q;q.name=TfToken("privateUniform");q.interpolation=TfToken("uniform");q.type=TfToken("int");q.i={18,19};s.extraCurve={maskPlane, q};i.geometry.alreadyDeformed=true;i.geometry.curveTopology={UsdGenDeviceCurveType::Cubic,UsdGenDeviceCurveBasis::BSpline,UsdGenDeviceCurveWrap::Pinned};i.geometry.tiles={{3,0,2,0,7}};uint32_t named[]={73,81};i.additionalNamed.push_back({{"namedCurve",UsdGenDeviceValueType::UInt32,UsdGenDeviceDomain::Primitive,2,1,4,true},Bytes(named,2)});return i; }
static std::shared_ptr<const VulkanSourceGeneration> Upload(std::shared_ptr<NativeOwner>const&n,VulkanSourceGenerationCreateInfo i){VkResult r=VK_SUCCESS;std::string why;auto u=VulkanSourceUpload::Create(std::move(i),&r,&why);if(!u||u->Submit()!=SourceGenerationStatus::Submitted||!Prove(n)||u->Poll()!=SourceGenerationStatus::Ready)return{};return u->TakeReady();}
}
int main(int argc,char**argv){
 CheckUlpBounds();
 CHECK(argc==5);auto scale=Code(argv[1]),set=Code(argv[2]),cut=Code(argv[3]),reparam=Code(argv[4]);CHECK(!scale.empty()&&!set.empty()&&!cut.empty()&&!reparam.empty());bool unavailable=false;auto native=CreateNative(&unavailable);if(unavailable)return 77;CHECK(native);VkPhysicalDeviceProperties props{};vkGetPhysicalDeviceProperties(native->physical,&props);if(props.limits.maxPerStageDescriptorStorageBuffers<5||props.limits.maxDescriptorSetStorageBuffers<5||props.limits.maxPushConstantsSize<20)return 77;
 DeviceContext::CreateInfo ci;ci.instance=native->instance;ci.physicalDevice=native->physical;ci.device=native->device;ci.computeQueue=native->queue;ci.computeQueueFamily=native->family;ci.physicalIndex=native->physicalIndex;ci.resourceDeviceId=7933;ci.nativeLifetime=native;ci.resources={size_t{32}<<20,0};auto context=DeviceContext::Create(ci);CHECK(context);auto pool=context->resources();auto ledger=pool->Snapshot();VkResult status=VK_SUCCESS;auto base=Upload(native,Source(context));CHECK(base);auto pipe=LengthScalePipeline::CreateWithReparam(context,scale,set,cut,reparam,&status);CHECK(pipe&&pipe->HasReparam());auto oldCut=LengthScalePipeline::CreateWithCutExtend(context,scale,set,cut,&status);CHECK(oldCut&&oldCut->HasCutExtend()&&!oldCut->HasReparam());
 auto runRaw=[&](std::shared_ptr<const ChargedBuffer> points,std::shared_ptr<const ChargedBuffer> offsets,std::shared_ptr<const ChargedBuffer> hair,uint32_t curves,uint32_t pointsCount,float value,bool absolute){auto c=pipe->BeginReparam(std::move(points),std::move(offsets),std::move(hair),curves,pointsCount,value,absolute,&status);if(!c||status!=VK_SUCCESS||!Prove(native))return std::make_pair(std::unique_ptr<LengthScalePipeline::Candidate>{},UINT32_MAX);uint32_t sem=UINT32_MAX;if(c->Poll(&sem)!=VK_SUCCESS)return std::make_pair(std::unique_ptr<LengthScalePipeline::Candidate>{},UINT32_MAX);return std::pair<std::unique_ptr<LengthScalePipeline::Candidate>,uint32_t>(std::move(c),sem);};
 auto run=[&](std::shared_ptr<const VulkanSourceGeneration>const&g,float value,bool absolute){return runRaw(g->PlaneOwner("points"),g->PlaneOwner("curveOffsets"),g->PlaneOwner("hairT"),g->curveCount(),g->pointCount(),value,absolute);};
 auto sameLedger=[&](UsdGenExecutionResourceSnapshot const&a,UsdGenExecutionResourceSnapshot const&b){return a.limitBytes==b.limitBytes&&a.headroomBytes==b.headroomBytes&&a.usableBytes==b.usableBytes&&a.usedBytes==b.usedBytes&&a.byKind==b.byKind;};
 auto oldBefore=pool->Snapshot();unsigned oldHooks=0;auto oldMissing=oldCut->BeginReparam(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),base->PlaneOwner("hairT"),base->curveCount(),base->pointCount(),4,true,&status,[&]{++oldHooks;return true;});CHECK(!oldMissing&&status==VK_ERROR_FEATURE_NOT_PRESENT&&oldHooks==0&&sameLedger(pool->Snapshot(),oldBefore));
 Packet original;CHECK(Capture(native,context,base,&original));CHECK(original.count("stableIds")&&original.count("privateVertex")&&original.count("sourceRootT"));
 auto check=[&](std::shared_ptr<const VulkanSourceGeneration>const&child,float const*expect){CHECK(child&&child->PlaneOwner("points")!=base->PlaneOwner("points"));for(auto const&p:base->planes())if(p.metadata.name!="points")CHECK(child->PlaneOwner(p.metadata.name)==base->PlaneOwner(p.metadata.name));for(auto const&f:base->sourceFrames())CHECK(child->SourceFrameOwner(f.metadata.name)==base->SourceFrameOwner(f.metadata.name));CHECK(child->geometry().alreadyDeformed==base->geometry().alreadyDeformed&&child->geometry().curveTopology.type==base->geometry().curveTopology.type&&child->geometry().curveTopology.basis==base->geometry().curveTopology.basis&&child->geometry().curveTopology.wrap==base->geometry().curveTopology.wrap&&child->geometry().tiles.size()==base->geometry().tiles.size());for(size_t j=0;j<child->geometry().tiles.size();++j){auto const&a=child->geometry().tiles[j];auto const&b=base->geometry().tiles[j];CHECK(a.tile==b.tile&&a.firstCurve==b.firstCurve&&a.curveCount==b.curveCount&&a.firstPoint==b.firstPoint&&a.pointCount==b.pointCount&&a.extentMin==b.extentMin&&a.extentMax==b.extentMax&&a.boundsValid==b.boundsValid);}CHECK(child->chunks().size()==base->chunks().size());auto const&a=child->chunks()[0];auto const&b=base->chunks()[0];CHECK(a.firstCurve==b.firstCurve&&a.curveCount==b.curveCount&&a.liveCount==b.liveCount&&a.firstCv==b.firstCv&&a.cvCount==b.cvCount&&a.tile==b.tile&&a.surface==b.surface);Packet got;CHECK(Capture(native,context,child,&got)&&got.size()==original.size());for(auto const&p:original)if(p.first!="points")CHECK(got.at(p.first)==p.second);CHECK(CheckPoints(got.at("points"),expect));};
 auto child=[&](LengthScalePipeline::Candidate const&c,uint64_t v){std::string why;return VulkanSourceGeneration::WithPoints(base,c,v,&why);};
 auto equal=run(base,4,true);CHECK(equal.first&&equal.second==0&&equal.first->succeeded()&&equal.first->usesReparam()&&equal.first->hairTOwner()==base->PlaneOwner("hairT"));auto equalChild=child(*equal.first,18);float e[]={0,0,0,1,2,0,1,3,0,12,0,0,10,0,0,13,0,0,11,0,0};check(equalChild,e);CHECK(equalChild->topologyVersion()==base->topologyVersion()&&equalChild->valueVersion()==18);Packet equalInitial;CHECK(Capture(native,context,equalChild,&equalInitial));
 auto omitted=runRaw(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),{},base->curveCount(),base->pointCount(),4,true);CHECK(omitted.first&&omitted.second==0&&omitted.first->succeeded()&&omitted.first->usesReparam()&&!omitted.first->hairTOwner()&&!VulkanSourceGeneration::WithPoints(base,*omitted.first,30));
 auto foreign=Upload(native,Source(context));CHECK(foreign&&foreign->PlaneOwner("hairT")!=base->PlaneOwner("hairT"));Packet foreignPacket;CHECK(Capture(native,context,foreign,&foreignPacket)&&foreignPacket.at("hairT")==original.at("hairT"));auto foreignHair=runRaw(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),foreign->PlaneOwner("hairT"),base->curveCount(),base->pointCount(),4,true);CHECK(foreignHair.first&&foreignHair.second==0&&foreignHair.first->succeeded()&&foreignHair.first->usesReparam()&&foreignHair.first->hairTOwner()==foreign->PlaneOwner("hairT")&&!VulkanSourceGeneration::WithPoints(base,*foreignHair.first,31));
 auto scaleOne=run(base,1,false);CHECK(scaleOne.first&&scaleOne.second==0&&scaleOne.first->succeeded());auto scaleChild=child(*scaleOne.first,19);check(scaleChild,e);
 auto extend=run(base,8,true);CHECK(extend.first&&extend.second==0&&extend.first->succeeded());auto extendChild=child(*extend.first,20);float x[]={0,0,0,1,5,0,1,7,0,14,0,0,10,0,0,16,0,0,18,0,0};check(extendChild,x);Packet reread,equalLater;CHECK(Capture(native,context,base,&reread)&&reread==original&&Capture(native,context,equalChild,&equalLater)&&equalLater==equalInitial);
 auto fallback=Upload(native,Source(context,false,true));CHECK(fallback&&!fallback->PlaneOwner("hairT"));auto f=run(fallback,4,true);CHECK(f.first&&f.second==0&&f.first->succeeded()&&f.first->usesReparam()&&!f.first->hairTOwner());std::string why;auto fchild=VulkanSourceGeneration::WithPoints(fallback,*f.first,18,&why);CHECK(fchild&&!fchild->PlaneOwner("hairT"));Packet fp;CHECK(Capture(native,context,fchild,&fp));float fv[]={0,0,0, 1,1,0, 1,3,0, 10,0,0, 11.333333333f,0,0, 12.666666667f,0,0, 14,0,0};CHECK(CheckPoints(fp.at("points"),fv));
 auto badHair=[&](float value){VkBufferCreateInfo bi{};bi.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;bi.size=base->pointCount()*sizeof(float);bi.usage=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;auto hair=ChargedBuffer::Create(context,bi,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,UsdGenExecutionResourceKind::Scratch);CHECK(hair);void*mapped=nullptr;CHECK(vkMapMemory(native->device,hair->memory(),0,bi.size,0,&mapped)==VK_SUCCESS);for(uint32_t i=0;i<base->pointCount();++i)static_cast<float*>(mapped)[i]=value;vkUnmapMemory(native->device,hair->memory());auto candidate=runRaw(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),hair,base->curveCount(),base->pointCount(),4,true);CHECK(candidate.first&&candidate.second!=0&&!candidate.first->succeeded()&&!candidate.first->output());candidate.first.reset();hair.reset();};badHair(-.1f);badHair(1.1f);badHair(std::numeric_limits<float>::quiet_NaN());badHair(std::numeric_limits<float>::infinity());
 auto tinyInfo=Source(context);tinyInfo.source.px={0,1e-30f,2e-30f,0,1e-30f,2e-30f,3e-30f};tinyInfo.source.py=VtFloatArray(7,0);auto tiny=Upload(native,std::move(tinyInfo));CHECK(tiny);Packet tinyOriginal,tinyAfter,tinyOutput;CHECK(Capture(native,context,tiny,&tinyOriginal));auto tinyCollapse=run(tiny,0,true);CHECK(tinyCollapse.first&&tinyCollapse.second==0&&tinyCollapse.first->succeeded()&&tinyCollapse.first->output());std::string tinyWhy;auto tinyChild=VulkanSourceGeneration::WithPoints(tiny,*tinyCollapse.first,32,&tinyWhy);CHECK(tinyChild&&Capture(native,context,tinyChild,&tinyOutput)&&tinyOutput.at("points")==std::vector<uint8_t>(21*sizeof(float),0)&&Capture(native,context,tiny,&tinyAfter)&&tinyAfter==tinyOriginal);
 auto preflight=pool->Snapshot();unsigned preHooks=0;auto invalidHair=[&](std::shared_ptr<const ChargedBuffer> hair,UsdGenExecutionResourceSnapshot const&before){auto c=pipe->BeginReparam(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),std::move(hair),base->curveCount(),base->pointCount(),4,true,&status,[&]{++preHooks;return true;});CHECK(!c&&status==VK_ERROR_INITIALIZATION_FAILED&&preHooks==0&&sameLedger(pool->Snapshot(),before));};{VkBufferCreateInfo wrongInfo{};wrongInfo.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;wrongInfo.size=base->pointCount()*sizeof(float)-sizeof(float);wrongInfo.usage=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;wrongInfo.sharingMode=VK_SHARING_MODE_EXCLUSIVE;auto wrongExtent=ChargedBuffer::Create(context,wrongInfo,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,UsdGenExecutionResourceKind::Scratch);CHECK(wrongExtent);auto before=pool->Snapshot();invalidHair(wrongExtent,before);}{VkBufferCreateInfo wrongInfo{};wrongInfo.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;wrongInfo.size=base->pointCount()*sizeof(float);wrongInfo.usage=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;wrongInfo.sharingMode=VK_SHARING_MODE_EXCLUSIVE;auto wrongUsage=ChargedBuffer::Create(context,wrongInfo,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,UsdGenExecutionResourceKind::Scratch);CHECK(wrongUsage);auto before=pool->Snapshot();invalidHair(wrongUsage,before);}CHECK(sameLedger(pool->Snapshot(),preflight));{auto foreignContext=DeviceContext::Create(ci);CHECK(foreignContext);VkBufferCreateInfo foreignInfo{};foreignInfo.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;foreignInfo.size=base->pointCount()*sizeof(float);foreignInfo.usage=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;foreignInfo.sharingMode=VK_SHARING_MODE_EXCLUSIVE;auto foreignHair=ChargedBuffer::Create(foreignContext,foreignInfo,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,UsdGenExecutionResourceKind::Scratch);CHECK(foreignHair);auto before=pool->Snapshot();invalidHair(foreignHair,before);}CHECK(sameLedger(pool->Snapshot(),preflight));
 auto admissionBefore=pool->Snapshot();auto pressure=pool->TryReserve(admissionBefore.usableBytes-admissionBefore.usedBytes,UsdGenExecutionResourceKind::Scratch);CHECK(pressure);auto saturated=pool->Snapshot();unsigned pressureHooks=0;auto pressureCandidate=pipe->BeginReparam(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),base->PlaneOwner("hairT"),base->curveCount(),base->pointCount(),4,true,&status,[&]{++pressureHooks;return true;});CHECK(!pressureCandidate&&status==VK_ERROR_OUT_OF_DEVICE_MEMORY&&pressureHooks==0&&sameLedger(pool->Snapshot(),saturated));pressure->Release();CHECK(sameLedger(pool->Snapshot(),admissionBefore));auto hookBefore=pool->Snapshot();unsigned hooks=0;auto hookFalse=pipe->BeginReparam(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),base->PlaneOwner("hairT"),base->curveCount(),base->pointCount(),4,true,&status,[&]{++hooks;return false;});CHECK(!hookFalse&&status==VK_ERROR_OUT_OF_DEVICE_MEMORY&&hooks==1&&sameLedger(pool->Snapshot(),hookBefore));auto hookThrow=pipe->BeginReparam(base->PlaneOwner("points"),base->PlaneOwner("curveOffsets"),base->PlaneOwner("hairT"),base->curveCount(),base->pointCount(),4,true,&status,[&]() -> bool{++hooks;throw 1;});CHECK(!hookThrow&&status==VK_ERROR_UNKNOWN&&hooks==2&&sameLedger(pool->Snapshot(),hookBefore));
 auto zero=Upload(native,Source(context,true));CHECK(zero);auto bad=run(zero,2,true);CHECK(bad.first&&bad.second!=0&&!bad.first->succeeded()&&!bad.first->output()&&!VulkanSourceGeneration::WithPoints(zero,*bad.first,18));auto zeroOK=run(zero,0,true);CHECK(zeroOK.first&&zeroOK.second==0&&zeroOK.first->succeeded());auto empty=pipe->BeginReparam({}, {}, {},0,0,1,true,&status);CHECK(empty&&empty->succeeded());
 empty.reset();zeroOK.first.reset();bad.first.reset();zero.reset();tinyChild.reset();tinyCollapse.first.reset();tiny.reset();foreignHair.first.reset();foreign.reset();omitted.first.reset();fchild.reset();f.first.reset();fallback.reset();extendChild.reset();extend.first.reset();scaleChild.reset();scaleOne.first.reset();equalChild.reset();equal.first.reset();oldCut.reset();pipe.reset();base.reset();CHECK(sameLedger(pool->Snapshot(),ledger));std::puts("Vulkan reparam Length COW: PASS");return 0;
}
