#include "gpu/rootFrameGather.h"

#include <cuda_runtime.h>

#include <cstring>
#include <cstdio>
#include <vector>

using namespace usdGen::gpu;
#define CHECK(x) do { if (!(x)) { std::fprintf(stderr,"FAIL %s:%d: %s\n",__FILE__,__LINE__,#x); return 1; } } while(false)
template<class T> bool Upload(DeviceBuffer<T>& b,std::vector<T> const& h,cudaStream_t s){return b.reset(h.size())==cudaSuccess&&(!h.size()||cudaMemcpyAsync(b.data(),h.data(),h.size()*sizeof(T),cudaMemcpyHostToDevice,s)==cudaSuccess);} template<class T> DeviceView<const T> View(DeviceBuffer<T> const& b){return b.view();} template<class T> bool Download(DeviceView<const T> d,std::vector<T>* h,cudaStream_t s){h->resize(d.size);return(!d.size||cudaMemcpyAsync(h->data(),d.data,d.size*sizeof(T),cudaMemcpyDeviceToHost,s)==cudaSuccess)&&cudaStreamSynchronize(s)==cudaSuccess;}
float3 V(float x,float y,float z){return make_float3(x,y,z);} bool SameBits(float3 a,float3 b){return std::memcmp(&a,&b,sizeof(a))==0;}
int main(){cudaStream_t producer=nullptr,consumer=nullptr;CHECK(cudaStreamCreateWithFlags(&producer,cudaStreamNonBlocking)==cudaSuccess&&cudaStreamCreateWithFlags(&consumer,cudaStreamNonBlocking)==cudaSuccess);{
 DeviceBuffer<uint64_t> sourceIds,survivors,bad; DeviceBuffer<float3> origins,t,b,n; DeviceBuffer<uint8_t> valid,drop;
 CHECK(Upload(sourceIds,{11,42,99},producer)&&Upload(survivors,{11,42,99},producer)&&Upload(origins,{V(-0.0f,0,0),V(4,0,0),V(9,0,0)},producer)&&Upload(t,{V(-0.0f,0,0),V(2,0,0),V(3,0,0)},producer)&&Upload(b,{V(0,-0.0f,0),V(0,2,0),V(0,3,0)},producer)&&Upload(n,{V(0,0,-0.0f),V(0,0,2),V(0,0,3)},producer)&&Upload(valid,{1,0,1},producer)&&Upload(drop,{0,1,0},producer));
 RestRootFrames source{View(t),View(b),View(n)}; CudaRootFrameGather gather;
 CHECK(gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::Ok&&gather.count()==3);
 std::vector<float3> outO,outT,outB,outN;std::vector<uint8_t> outV,outD;CHECK(Download(gather.origins(),&outO,producer)&&Download(gather.frames().tangent,&outT,producer)&&Download(gather.frames().binormal,&outB,producer)&&Download(gather.frames().normal,&outN,producer)&&Download(gather.valid(),&outV,producer)&&Download(gather.dropMask(),&outD,producer));
 CHECK(SameBits(outO[0],V(-0.0f,0,0))&&SameBits(outO[1],V(4,0,0))&&SameBits(outO[2],V(9,0,0))&&SameBits(outT[0],V(-0.0f,0,0))&&SameBits(outT[2],V(3,0,0))&&SameBits(outB[0],V(0,-0.0f,0))&&SameBits(outN[0],V(0,0,-0.0f))&&outV==std::vector<uint8_t>({1,0,1})&&outD==std::vector<uint8_t>({0,1,0})); uint64_t generation=gather.generation();
 DeviceBuffer<float3> consumerOld; CHECK(consumerOld.reset(3)==cudaSuccess&&gather.waitOn(consumer)==cudaSuccess&&cudaMemcpyAsync(consumerOld.data(),gather.frames().tangent.data,3*sizeof(float3),cudaMemcpyDeviceToDevice,consumer)==cudaSuccess&&gather.recordUse(consumer)==cudaSuccess);
 CHECK(Upload(survivors,{11},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::Ok); std::vector<float3> old; CHECK(Download(View(consumerOld),&old,consumer)&&old.size()==3&&SameBits(old[0],V(-0.0f,0,0))&&SameBits(old[2],V(3,0,0))); generation=gather.generation();
 CHECK(Upload(bad,{11,77},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(bad),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::MissingStableId&&gather.generation()==generation);
 CHECK(Upload(bad,{1},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(bad),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::MissingStableId&&gather.generation()==generation);
 CHECK(Upload(bad,{100},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(bad),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::MissingStableId&&gather.generation()==generation);
 CHECK(Upload(bad,{99,11},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(bad),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::InvalidArgument&&gather.generation()==generation);
 CHECK(Upload(bad,{11,11},producer)&&gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),View(bad),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::InvalidArgument&&gather.generation()==generation);
 CHECK(Upload(bad,{11,42,42},producer)&&gather.Apply(View(bad),source,View(origins),View(valid),View(drop),View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::InvalidArgument&&gather.generation()==generation);
 CHECK(Upload(bad,{42,11,99},producer)&&gather.Apply(View(bad),source,View(origins),View(valid),View(drop),View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::InvalidArgument&&gather.generation()==generation);
 std::vector<uint64_t> largeIds(513);std::vector<float3> largeFrames(513,V(1,0,0));std::vector<uint8_t> largeFlags(513,1);for(size_t i=0;i<largeIds.size();++i)largeIds[i]=1000+i;largeIds[400]=largeIds[399];DeviceBuffer<uint64_t> largeIdBuffer;DeviceBuffer<float3> largeOrigin,largeT,largeB,largeN;DeviceBuffer<uint8_t> largeValid,largeDrop;CHECK(Upload(largeIdBuffer,largeIds,producer)&&Upload(largeOrigin,largeFrames,producer)&&Upload(largeT,largeFrames,producer)&&Upload(largeB,largeFrames,producer)&&Upload(largeN,largeFrames,producer)&&Upload(largeValid,largeFlags,producer)&&Upload(largeDrop,largeFlags,producer));RestRootFrames largeSource{View(largeT),View(largeB),View(largeN)};CHECK(gather.Apply(View(largeIdBuffer),largeSource,View(largeOrigin),View(largeValid),View(largeDrop),View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::InvalidArgument&&gather.generation()==generation);
 CHECK(gather.Apply(View(sourceIds),source,View(origins),View(valid),View(drop),{},producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::Ok&&gather.count()==0);
 CHECK(gather.Apply({},RestRootFrames{}, {}, {}, {},View(survivors),producer)==RootFrameGatherStatus::Ok&&gather.Finish(producer)==RootFrameGatherStatus::MissingStableId);
 }CHECK(cudaStreamDestroy(producer)==cudaSuccess&&cudaStreamDestroy(consumer)==cudaSuccess);std::puts("testUsdGenCudaRootFrameGather: PASS");return 0;}
