#!/usr/bin/env python3
"""M1 benchmark/fixture groom scenes G1-G5 (plan/09 section 0.3).

Five deterministic fixtures under usd/fixtures/:

| File              | Curves    | CVs   | Surface grid   |
|-------------------|-----------|-------|----------------|
| g1_lash4k.usda    | 4 000     | 32k   | 64 x 64 quads  |
| g2_brow40k.usda   | 40 000    | 320k  | 200 x 200      |
| g3_head100k.usda  | 100 000   | 800k  | 400 x 250      |
| g4_fur200k.usda   | 200 000   | 1.6M  | 500 x 400      |
| g5_head1M.usda    | 1 000 000 | 8.0M  | 1000 x 1000    |

Each scene: a UsdGenGroom with a UsdGeomMesh scalp surface and one
UsdGenDescription carrying the frozen M1 5-op chain
Scatter -> Grow -> Noise -> Length -> Width wired by explicit
rel usdGen:input (02-schema.md section 0.3: no implicit ordering), and
rel usdGen:terminal pointing at the Width op.

Density calibration: UsdGenScatter emits per face
  n_f = floor(density * area_f) (+1 iff frac-draw < frac(expected)),
so with a unit-area quad grid, density = curves / faces exactly.
All five grooms use integer densities (exact counts, no frac draws);
G3 uses density 1.0 (one root per face).

Grow uses usdGen:segments = 8, i.e. 8 CVs per curve (EV-008's ladder:
G1 = 32k CVs, G3 = 800k CVs).

Only C1-registered properties are authored (docs/freezes/C1.md section 2
/ libs/usdGenSchema/schema.usda); every value is inside the kernel
Bind() ranges (segments in [2,64], octaves in [1,6], lacunarity > 1,
gain in [0,1], taper/taperStart in [0,1]).

Determinism: grid coordinates are short decimals, parameters are
literals, emission order is fixed -- two runs are byte-identical.

Regenerate: python3 usd/fixtures/make_fixtures.py
"""

import os
import sys

# (filename, curves, nx, ny, surface size, scatter seed)
GROOMS = [
    ("g1_lash4k.usda", 4000, 80, 50, 8.0, 11),
    ("g2_brow40k.usda", 40000, 200, 200, 20.0, 12),
    ("g3_head100k.usda", 100000, 400, 250, 40.0, 13),
    ("g4_fur200k.usda", 200000, 500, 400, 50.0, 14),
    ("g5_head1M.usda", 1000000, 1000, 1000, 100.0, 15),
]

SEGMENTS = 8
CHAIN_SEED = 7


def _fmt(f):
    s = "%.4g" % f
    return "0" if s == "-0" else s


def _mesh_block(nx, ny, size):
    # Unit-area quads (1.0 x 1.0): UsdGenScatter emits
    # n_f = floor(density * area_f) per face, so density * 1.0 is exact.
    # `size` only recenters the grid; it does not change face areas.
    dx = 1.0
    dz = 1.0
    npx = nx + 1
    lines = []
    lines.append("        int[] faceVertexCounts = [%s]" % ", ".join(["4"] * (nx * ny)))
    idx = []
    for j in range(ny):
        for i in range(nx):
            v = j * npx + i
            # CCW seen from +Y (normal UP): UsdGenGrow's default
            # direction="surfaceNormal" grows hair along the normal, so a
            # downward (clockwise) winding would plant the groom UNDER the
            # scalp (2026-09-12: thatch render). Order is a->d->c->b.
            idx += [v, v + npx, v + npx + 1, v + 1]
    lines.append("        int[] faceVertexIndices = [%s]" % ", ".join(str(k) for k in idx))
    pts = []
    for j in range(ny + 1):
        for i in range(npx):
            pts.append("(%s, 0, %s)" % (_fmt(i - nx / 2.0), _fmt(j - ny / 2.0)))
    lines.append("        point3f[] points = [%s]" % ", ".join(pts))
    st = []
    for j in range(ny + 1):
        for i in range(npx):
            st.append("(%s, %s)" % (_fmt(i / nx), _fmt(j / ny)))
    lines.append("        texCoord2f[] primvars:st = [%s] (" % ", ".join(st))
    lines.append('            interpolation = "vertex"')
    lines.append("        )")
    return "\n".join(lines + [""])


def render(name, curves, nx, ny, size, seed):
    faces = nx * ny
    assert curves % faces == 0, (
        "%s: %d curves not divisible by %d faces" % (name, curves, faces))
    density = curves // faces
    label = name.replace(".usda", "")
    out = []
    out.append("#usda 1.0")
    out.append("(")
    out.append('    defaultPrim = "Groom"')
    out.append("    metersPerUnit = 1")
    out.append('    upAxis = "Y"')
    out.append('    documentation = "M1 fixture %s: %d curves x 8 CV. '
               'Generated by usd/fixtures/make_fixtures.py; do not hand-edit."'
               % (name, curves))
    out.append(")")
    out.append("")
    out.append('def UsdGenGroom "Groom"')
    out.append("{")
    out.append("    uniform int usdGen:schemaVersion = 1")
    out.append('    uniform string usdGen:sessionId = "bench"')
    out.append('    string usdGen:label = "%s"' % label)
    out.append("    rel usdGen:surface = </Groom/Scalp>")
    out.append("")
    out.append('    def Mesh "Scalp"  # NOT UsdGeomMesh: the USD type name is Mesh')
    out.append("    {")
    out.append('        uniform token subdivisionScheme = "none"')
    out.append(_mesh_block(nx, ny, size))
    out.append("    }")
    out.append("")
    out.append('    def UsdGenDescription "Description"')
    out.append("    {")
    out.append("        uniform int usdGen:tileTarget = 64")
    out.append("        rel usdGen:surface = </Groom/Scalp>")
    out.append("        rel usdGen:terminal = </Groom/Description/Width>")
    out.append('        string usdGen:label = "%s"' % label)
    out.append("")
    out.append('        def UsdGenScatter "Scatter"')
    out.append("        {")
    out.append("            uniform int usdGen:seed = %d" % seed)
    out.append("            float usdGen:density = %s" % float(density))
    out.append("        }")
    out.append("")
    out.append('        def UsdGenGrow "Grow"')
    out.append("        {")
    out.append("            uniform int usdGen:seed = %d" % CHAIN_SEED)
    out.append("            rel usdGen:input = </Groom/Description/Scatter>")
    out.append("            int usdGen:segments = 8")
    out.append("            float usdGen:length = 1.0")
    out.append("        }")
    out.append("")
    out.append('        def UsdGenNoise "Noise"')
    out.append("        {")
    out.append("            uniform int usdGen:seed = %d" % CHAIN_SEED)
    out.append("            rel usdGen:input = </Groom/Description/Grow>")
    out.append("            float usdGen:noise:magnitude = 0.05")
    out.append("            float usdGen:noise:frequency = 3.0")
    out.append("        }")
    out.append("")
    out.append('        def UsdGenLength "Length"')
    out.append("        {")
    out.append("            uniform int usdGen:seed = %d" % CHAIN_SEED)
    out.append("            rel usdGen:input = </Groom/Description/Noise>")
    out.append("            float usdGen:length:value = 1.0")
    out.append("        }")
    out.append("")
    out.append('        def UsdGenWidth "Width"')
    out.append("        {")
    out.append("            uniform int usdGen:seed = %d" % CHAIN_SEED)
    out.append("            rel usdGen:input = </Groom/Description/Length>")
    out.append("            float usdGen:width = 0.01")
    out.append("        }")
    out.append("    }")
    out.append("}")
    out.append("")
    # Framing camera (benchUsdGenStorm auto-uses the first UsdGeomCamera):
    # above and in front of the scalp centre, pitched down at the origin so
    # the whole unit-quad grid plus hair length is in frame. Parametric in
    # the grid extent so G1..G5 all frame. NOT groom content (outside Groom).
    import math
    extent = float(max(nx, ny))
    dist = extent * 1.35
    height = dist * 0.45
    pitch = -math.degrees(math.atan2(height, dist))
    out.append('def Camera "Cam"')
    out.append("{")
    out.append("    float focalLength = 35")
    out.append("    float horizontalAperture = 36")
    out.append("    float2 clippingRange = (%s, %s)"
               % (_fmt(dist / 100.0), _fmt(dist * 20.0)))
    out.append("    double3 xformOp:translate = (0, %s, %s)"
               % (_fmt(height), _fmt(dist)))
    out.append("    float3 xformOp:rotateXYZ = (%s, 0, 0)" % _fmt(pitch))
    out.append('    uniform token[] xformOpOrder = ["xformOp:translate", '
               '"xformOp:rotateXYZ"]')
    out.append("}")
    out.append("")
    return "\n".join(out)


def main():
    root = os.path.dirname(os.path.abspath(__file__))
    for name, curves, nx, ny, size, seed in GROOMS:
        out = os.path.join(root, name)
        with open(out, "w") as f:
            f.write(render(name, curves, nx, ny, size, seed))
        print("wrote %s (%d bytes): %d curves x %d CV, %dx%d surface, seed %d"
              % (out, os.path.getsize(out), curves, SEGMENTS, nx, ny, seed))


if __name__ == "__main__":
    sys.exit(main())
