#include "deformCurves.h"
#include <cmath>
namespace usdGen { namespace gpu { namespace {
__global__ void validateShape(const uint32_t* o,int curves,int points,const float3* roots,int* bad){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i==0&&(o[0]!=0||o[curves]!=(uint32_t)points))atomicExch(bad,1);if(i<curves){uint32_t a=o[i],b=o[i+1];float3 r=roots[i];if(a>=b||b>(uint32_t)points||!isfinite(r.x)||!isfinite(r.y)||!isfinite(r.z))atomicExch(bad,1);}}
__global__ void rootLockBlend(const float3* rest,const float3* warp,const uint32_t* off,const float3* target,int curves,float groom,const float* prim,const float* point,float3* out,int* bad){int c=blockIdx.x*blockDim.x+threadIdx.x;if(c>=curves)return;uint32_t a=off[c],b=off[c+1];float pe=prim?prim[c]:1.f;if(!isfinite(pe))atomicExch(bad,1);float3 d=make_float3(target[c].x-warp[a].x,target[c].y-warp[a].y,target[c].z-warp[a].z);for(uint32_t i=a;i<b;++i){float qenv=point?point[i]:1.f;float raw=groom*pe*qenv;if(!isfinite(qenv)||!isfinite(raw)){atomicExch(bad,1);continue;}if(raw<=0.f){out[i]=rest[i];continue;}float e=fminf(1.f,raw);float3 q=make_float3(warp[i].x+d.x,warp[i].y+d.y,warp[i].z+d.z);float3 result=make_float3(rest[i].x+(q.x-rest[i].x)*e,rest[i].y+(q.y-rest[i].y)*e,rest[i].z+(q.z-rest[i].z)*e);if(!isfinite(result.x)||!isfinite(result.y)||!isfinite(result.z)){atomicExch(bad,1);continue;}out[i]=result;}}
}
CudaRbfCurveDeformer::~CudaRbfCurveDeformer(){if(ready_){cudaEventSynchronize(ready_);cudaEventDestroy(ready_);}}
RbfStatus CudaRbfCurveDeformer::Deform(CudaRbfBinding& r,DeviceCurveGeometryView g,DeviceView<const float3> targets,float envelope,DeviceView<const float> prim,DeviceView<const float> point,DeviceView<float3> out,cudaStream_t s){
 if(pending_||poisoned_||!g.points.data||!g.restPoints.data||!g.curveOffsets.data||!targets.data||!out.data||g.pointCount==0||g.pointCount>size_t(INT_MAX)||g.curveCount==0||g.curveCount>size_t(INT_MAX)||g.points.size!=g.pointCount||g.restPoints.size!=g.pointCount||g.curveOffsets.size!=g.curveCount+1||targets.size!=g.curveCount||out.size!=g.pointCount||(!prim.size&&prim.data)||(!point.size&&point.data)||(prim.size&&!prim.data)||(point.size&&!point.data)||(prim.size&&prim.size!=g.curveCount)||(point.size&&point.size!=g.pointCount)||!std::isfinite(envelope))return RbfStatus::InvalidArgument;
 if(!ready_&&cudaEventCreateWithFlags(&ready_,cudaEventDisableTiming)!=cudaSuccess)return RbfStatus::CudaError;
 if(flags_.reset(1)!=cudaSuccess||warped_.reset(g.pointCount)!=cudaSuccess||cudaMemsetAsync(flags_.data(),0,sizeof(int),s)!=cudaSuccess)return RbfStatus::CudaError;
 validateShape<<<(g.curveCount+255)/256,256,0,s>>>(g.curveOffsets.data,(int)g.curveCount,(int)g.pointCount,targets.data,flags_.data());int bad=0;if(cudaMemcpyAsync(&bad,flags_.data(),sizeof(bad),cudaMemcpyDeviceToHost,s)!=cudaSuccess||cudaStreamSynchronize(s)!=cudaSuccess)return RbfStatus::CudaError;if(bad)return RbfStatus::InvalidArgument;
 RbfStatus st=r.Evaluate(g.restPoints,warped_.view(),s);if(st!=RbfStatus::Ok)return st;
 const float* pp=prim.data;const float* qp=point.data;float3* dst=out.data;rootLockBlend<<<(g.curveCount+255)/256,256,0,s>>>(g.restPoints.data,warped_.data(),g.curveOffsets.data,targets.data,(int)g.curveCount,envelope,pp,qp,dst,flags_.data());if(cudaGetLastError()!=cudaSuccess||cudaEventRecord(ready_,s)!=cudaSuccess)return RbfStatus::CudaError;pending_=true;return RbfStatus::Ok;
}
RbfStatus CudaRbfCurveDeformer::Finish(CudaRbfBinding& r,cudaStream_t s){if(!pending_)return r.Finish(s);int bad=0;if(cudaStreamWaitEvent(s,ready_,0)!=cudaSuccess||cudaMemcpyAsync(&bad,flags_.data(),sizeof(bad),cudaMemcpyDeviceToHost,s)!=cudaSuccess||cudaStreamSynchronize(s)!=cudaSuccess)return RbfStatus::CudaError;pending_=false;RbfStatus st=r.Finish(s);if(st!=RbfStatus::Ok)return st;if(bad){poisoned_=true;return RbfStatus::NonFiniteInput;}return RbfStatus::Ok;}
}}
